class Languages {
  static Map<String, Map<String, String>> translations = {
    'ar': {
      'Welcome Laith Haitham Azzam': 'مرحبا',
      'Have A Nice Day At Work': 'أتمنى لك يوم جيد في العمل',
      'Illness and Vaccines': 'الأمراض و اللقحات',
      'Illness': 'الأمراض',
      'Vaccines': 'اللقحات',
      'Rewards and Penalties': 'المكافئات و العقوبات',
      'Rewards': 'المكافئات',
      'Penalties': 'العقوبات',
      'Attendance Today': 'حضور اليوم',
      'Employees\nAttendance': 'حضور الموظفين',
      'Students\nAttendance': 'حضور الطلاب',
      'Teachers\nAttendance': 'حظور المعلمين',
      'Percentage\nStudents': 'نسبة الطلاب',
      'Percentage\nTeacher': 'نسبة المعلمين',
      'Percentage\nEmployee': 'نسبة الموظفين',
      'Total Students': 'إجمالي الطلاب',
      'Total Teacher': 'إجمالي المعلمين',
      'Total Employee': 'إجمالي الموظفين',
      'Total Visitor': 'إجمالي الزائرين',
      'Total Books': 'إجمالي الكتب',
      'Total Division': 'إجمالي الشعب',
      'Dashboard': 'الإحصائيات',
      'Enroll Requests': 'طلبات التسجيل',
      'Exam Table': "جدول الامتحان",
      'School Time Table': 'جدول الدوام',
      'All Students': 'كل الطلاب',
      'Study Year Students': 'طلاب العام الدراسي',
      'All Guardians': 'أولياء الأمور',
      'Student Attendance': 'حضور الطلاب',
      'Students Attendance Managment': 'إدارة حضور الطلاب',
      'Teacher Management': 'إدارة المعلمين',
      'Teacher Status': 'حضور المعلمين',
      'Teacher Attendance Managment': 'إدارة حضور المعلمين',
      'Employee Management': 'إدارة الموظفين',
      'Employee Attendance': 'حضور الموظفين',
      'Employee Attendance Manage': 'إدارة حضور الموظفين',
      'Virtual User Management': 'إدارة الموظفين الافتراضيين',
      'Session Management': 'إدارة السنوات',
      'Grade Management': 'إدارة المراحل الدراسية',
      'Subject Management': 'إدارة المواد',
      'Class Management': 'إدارة الصفوف',
      'Division Management': 'إدارة الشعب',
      'Curriculum Management': 'إدارة المناهج',
      'School Data Management': 'إدارة معلومات المدرسة',
      'Electronic Library': 'المكتبة الإلكترونية',
      'Transaction': 'سجل المناقلات',
      'Illness Screen': 'الأمراض',
      'Vaccine Screen': 'اللقاحات',
      'Presence of students': 'نسب الطلاب',
      'Presence this session students': 'نسب طلاب هذا العام',
      'Total this year': 'إجمالي هذه السنة',
      'Add': 'إضافة',
      'Penalty En - Name': 'الاسم الإنكليزي للعقوبة',
      'Penalty Ar - Name': 'الاسم العربي للعقوبة',
      'Details': 'تفاصيل',
      'Add Penalty': 'إضافة عقوبة',
      'Delete': 'حذف',
      'Cancel': 'إلغاء',
      'Do You Want To Delete': 'هل تريد حذف العقوبة',
      'penalty': '',
      'Edit': 'تعديل',
      'Operation': 'العمليات',
      'Penalty Name': 'اسم العقوبة',
      'Delete Penalty': 'حذف العقوبة',
      'Edit Penalty': 'تعديل العقوبة',
      'Status': 'الحالة',
      'No Requests': 'لا يوجد طلبات',
      'Guardian Info :': 'معلومات ولي الأمر:',
      'Name :': 'الاسم:',
      'Mobile:': 'الهاتف:',
      'Email: ': 'البريد الإلكتروني: ',
      'National ID:': 'الرقم الوطني:',
      'Student Info:': 'معلومات الطالب:',
      'Current Class:': 'الصف الحالي:',
      'Previous Class:': 'الصف السابق',
      'Manage': 'إدارة',
      'Reject': 'رفض',
      'Approve': 'موافقة',
      'Rejected': 'مرفوض',
      'Pending': 'معلق',
      'Partially': 'جزئياً',
      'Search By Name': 'البحث حسب الاسم',
      'Class': 'صف',
      'Division': 'شعبة',
      'Manage Student': 'إدارة الطالب',
      'Add Exam': 'إضافة امتحان',
      'Date': 'التاريح',
      'Type': 'النوع',
      'Curriculum Name': 'اسم المنهاج',
      'Period': 'الفترة الزمنية',
      'Max Mark': 'العلامة العظمى',
      'Passing Mark': 'الحد الأدنى للنجاح',
      'Operations': 'العمليات',
      'Edit Exam': 'تعديل الامتحان',
      'Semester': 'الفصل',
      'Curriculum': 'المنهاج',
      'season': 'الفصل',
      'Min Mark': 'الحد الأدنى للنجاح',
    },
    'en': {
      'Welcome Laith Haitham Azzam': 'Welcome Laith Haitham Azzam',
      'Have A Nice Day At Work': 'Have A Nice Day At Work',
      'Illness and Vaccines': 'Illness and Vaccines',
      'Illness': 'Illness',
      'Vaccines': 'Vaccines',
      'Rewards and Penalties': 'Rewards and Penalties',
      'Rewards': 'Rewards',
      'Penalties': 'Penalties',
      'Attendance Today': 'Attendance Today',
      'Employees\nAttendance': 'Employees\nAttendance',
      'Students\nAttendance': 'Students\nAttendance',
      'Teachers\nAttendance': 'Teachers\nAttendance',
      'Percentage\nStudents': 'Percentage\nStudents',
      'Percentage\nTeacher': 'Percentage\nTeacher',
      'Percentage\nEmployee': 'Percentage\nEmployee',
      'Total Students': 'Total Students',
      'Total Teacher': 'Total Teacher',
      'Total Employee': 'Total Employee',
      'Total Visitor': 'Total Visitor',
      'Total Books': 'Total Books',
      'Total Division': 'Total Division',
      'Dashboard': 'Dashboard',
      'Enroll Requests': 'Enroll Requests',
      'Exam Table': "Exam Table",
      'School Time Table': 'School Time Table',
      'All Students': 'All Students',
      'Study Year Students': 'Study Year Students',
      'All Guardians': 'All Guardians',
      'Student Attendance': 'Student Attendance',
      'Students Attendance Managment': 'Students Attendance Managment',
      'Teacher Management': 'Teacher Management',
      'Teacher Status': 'Teacher Status',
      'Teacher Attendance Managment': 'Teacher Attendance Managment',
      'Employee Management': 'Employee Management',
      'Employee Attendance': 'Employee Attendance',
      'Employee Attendance Manage': 'Employee Attendance Manage',
      'Virtual User Management': 'Virtual User Management',
      'Session Management': 'Session Management',
      'Grade Management': 'Grade Management',
      'Subject Management': 'Subject Management',
      'Class Management': 'Class Management',
      'Division Management': 'Division Management',
      'Curriculum Management': 'Curriculum Management',
      'School Data Management': 'School Data Management',
      'Electronic Library': 'Electronic Library',
      'Transaction': 'Transaction',
      'Illness Screen': 'Illness Screen',
      'Vaccine Screen': 'Vaccine Screen',
      'Presence of students': 'Presence of students',
      'Presence this session students': 'Presence 2024 students',
      'Total this year': 'Total this year',
      'Add': 'Add',
      'Penalty En - Name': 'Penalty En - Name',
      'Penalty Ar - Name': 'Penalty Ar - Name',
      'Details': 'Details',
      'Add Penalty': 'Add Penalty',
      'Delete': 'Delete',
      'Cancel': 'Cancel',
      'Do You Want To Delete': 'Do You Want To Delete',
      'penalty': 'penalty',
      'Edit': 'Edit',
      'Operation': 'Operation',
      'Penalty Name': 'Penalty Name',
      'Delete Penalty': 'Delete Penalty',
      'Edit Penalty': 'Edit Penalty',
      'Status': 'Status',
      'No Requests': 'No Requests',
      'Guardian Info :': 'Guardian Info :',
      'Name :': 'Name :',
      'Mobile:': 'Mobile:',
      'Email: ': 'Email: ',
      'National ID:': 'National ID:',
      'Student Info:': 'Student Info:',
      'Current Class:': 'Current Class:',
      'Previous Class:': 'Previous Class',
      'Manage': 'Manage',
      'Reject': 'Reject',
      'Approve': 'Approve',
      'Rejected': 'Rejected',
      'Pending': 'Pending',
      'Partially': 'Partially',
      'Search By Name': 'Search By Name',
      'Class': 'Class',
      'Division': 'Division',
      'Manage Student': 'Manage Student',
      'Add Exam': 'Add Exam',
      'Date': 'Date',
      'Type': 'Type',
      'Curriculum Name': 'Curriculum Name',
      'Period': 'Period',
      'Max Mark': 'Max Mark',
      'Passing Mark': 'Passing Mark',
      'Operations': 'Operations',
      'Edit Exam': 'Edit Exam',
      'Semester': 'Semester',
      'Curriculum': 'Curriculum',
      'season': 'semester',
      'Min Mark': 'Min Mark',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
    }
  };
}
